### ISSUE TITLE
Armhf support? 

### ISSUE THREAD

**Issue by XxAcielxX** [nightah/docker-rutorrent#1]
Hello,

Does your has armhf architecture support? I don't like Sub-directories and chown on /downloads by linuxserver/rutorrent either.

Regards

**Comment by nightah** [comment]
I don't at this point but I can add an explicit tag if you like.
Which specific ARM architecture are you using `arm64` or `armhf`?

**Comment by XxAcielxX** [comment]
Using Raspberry Pi 3, so it's `armhf` Architecture. I'll really appreciate if you can add it. Thanks

**Comment by nightah** [comment]
@XxAcielxX can you try pull the latest tag now and let me know if that works for you please?

**Comment by XxAcielxX** [comment]
@nightah `docker pull nightah/rutorrent:latest` if I'm not wrong?

Sorry for asking as I'm new to Docker.

**Comment by nightah** [comment]
Yep that's right.

**Comment by XxAcielxX** [comment]
@nightah Everything installed and running smooth, but torrents are getting saved in `~/downloads/incoming/` where I have set it to  `~/downloads/`. They are not getting moved either after torrent gets completed. 

I thought the incoming folder wasn't supposed to be created.

**Comment by nightah** [comment]
You need to modify your `rtorrent.rc` file specifically line 14.
https://github.com/linuxserver/docker-rutorrent/blob/78fb97974f723f16818ab30eb2f901be2447c698/root/defaults/rtorrent.rc#L14

You can find the file in: `/config/rtorrent/rtorrent.rc`
