### ISSUE TITLE
ARM64/AArch64 Support needed now 

### ISSUE THREAD

**Issue by XxAcielxX** [nightah/docker-rutorrent#2]
Hello,

This is time I'm trying to install your image on AArch64 Armbian OS on NanoPC-T4 (RK3399) Board. Can you once again add tag for the ARM64/AArch64?

I'll really appreciate it. Regards~

**Comment by nightah** [comment]
There already is an arm64v8 tag in the repo. If you pull the `latest` tag this should automatically redirect you to the correct container.

**Comment by XxAcielxX** [comment]
> There already is an arm64v8 tag in the repo. If you pull the `latest` tag this should automatically redirect you to the correct container.

Ah yes, on the 3rd try I was able to get it working yesterday after posting here.

Weirdly it was throwing some errors. Anyways, all is working now. Thanks again.
